test_data:
  benign: ["datasets/temp_test_benign.json"]
  harmful: ["datasets/temp_test_harm.json"]

generation:
  temperature: 0.5
  max_new_tokens: 1024

checkpoint_dir: "layer_wise_analysis_20250913_234433"
layers: [0, 30, 31]