input_json_path: "mistral_output_20250914_202359/mistral_generated_outputs_llamaguard_eval.json"
output_json_path: "mistral_output_20250914_202359/mistral_generated_outputs_finalized.json"
checkpoint_dir: "mistral_output_20250914_202359"